routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog', function () {
    return view('articles.index');
});
Route::get('/shop', function () {
    return view('shop.index');
});
Auth::routes();
Route::get('cleaning-articles/{id}/{cat_slug}', 'CategoryController@single')->name('category.single');

Route::get('/', 'HomeController@index')->name('home');
Route::get('cleaning-articles', 'ArticleController@index')->name('blog.index');
Route::get('cleaning-articles/{id}/{cat_slug}/{article_slug}', 'ArticleController@single')->name('blog.single');



Route::get('london-services/{id}/{slug}', 'ServicesController@single')->name('services.single');









Route::namespace('Admin')->prefix('myrpanel')->middleware('isAdmin')->name('rpanel.')->group(function () {

    Route::get('/', function () {
        return view('rpanel.layouts.app');
    })->name('welcome');

    Route::resource('article','ArticleController');
    Route::resource('category','CategoryController');
    Route::resource('services','ServiceController');

    Route::post('uploadimage', 'ArticleController@uploadImage')->name('uploadimage');


});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function articles() {
        return $this->belongsToMany('App\Article','article_category');
    }

    public function urlslug() {
        $slug = url('cleaning-articles/'.$this->id . '/'. $this->slug . '/');

        return $slug;
    }

    public function parent() {
        return $this->belongsTo(static::class, 'parent_id');
    }

    //each category might have multiple children

    public function childrens() {
        return $this->hasMany(static::class, 'parent_id')->orderBy('name', 'asc');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Traits\UploadTrait;
use App\Article;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
class CategoryController extends Controller
{
    use UploadTrait;
    /**
     * Display a listing of the resource.
     *
     * @return view
     */
    public function index()
    {
        $categories = Category::all();



        return view('rpanel.blog.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return view
     */
    public function create()
    {
        $categories = Category::all();


        return view('rpanel.blog.category.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return RedirectResponse;
     */
    public function store(Request $request)
    {

        $category = new Category();

        $category->name = $request['name'];
        $category->slug = Str::slug($request['name'],'-');
        $category->description = $request['description'];

        if($request['parent_id']) {
            $category->parent_id = $request['parent_id'];
        }
        else {
            $category->parent_id = 0; // which means its root category

        }
        $category->seo_title = $request['seo_title'];
        $category->seo_description = $request['seo_description'];


        $category->save();

        return redirect()->route('rpanel.category.index')->with('success','Category Added');



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $allcats = Category::all();
        return view('rpanel.blog.category.edit',compact('category','allcats'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $category->name = $request['name'];
        $category->slug = $request['slug'];
        $category->description = $request['description'];
        $category->parent_id = $request['parent_id'];

        $category->seo_title = $request['seo_title'];
        $category->seo_description = $request['seo_description'];

        if ($request->has('cat_image')) {


            $image = $request->file('cat_image');
            $name = Str::slug($request['name'], '-') . '-'.Str::random(4);
            $folder = 'cats';
            // Upload image
            $uploaded =  $this->uploadOne($image, $folder, 'public_uploads', $name);


            Storage::delete($category->cat_image); //delete the old image

            $category->cat_image = $uploaded;
        }
        $category->save();

        return redirect()->route('rpanel.category.index')->with('success','Edited Done');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);

        $deleteImage = Storage::delete($category->cat_image);

        $category->delete();

        return redirect()->route('rpanel.category.index')->with('success','Removed');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }


    public function single($id,$cat_slug)
    {
        $category = Category::find($id);

        return view('category.single',compact('category'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/rpanel/blog/category/create.blade.php
@extends('rpanel.layouts.app')

@section('title','New Category')

@section('content')
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">New Category</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <form action="{{route('rpanel.category.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-lg-7">
                            @method('post')

                            <div class="card card-success">
                                <div class="card-header">
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                                class="fas fa-minus"></i></button>
                                        <button type="button" class="btn btn-tool"
                                                data-card-widget="remove"><i class="fas fa-times"></i></button>
                                    </div>
                                    <h3 class="card-title">General</h3>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <small>Name</small>
                                            <div class="input-group mb-3">
                                                <input type="text" class="form-control" value=""
                                                       name="name">

                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <p>SLUG (editable after)</p>
                                            <div class="input-group mb-3">


                                                <input type="text" class="form-control" value=""
                                                       name="slug" disabled>

                                            </div>
                                        </div>

                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label>Main Category</label>
                                                        <select class="form-control" name="parent_id">
                                                            <option value="0" selected>No</option>
                                                            @forelse($categories as $category)
                                                                <option value="{{$category->id}}">{{$category->name}}</option>
                                                            @empty
                                                            @endforelse
                                                        </select>
                                                    </div>

                                                </div>


                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label> Description</label>
                                                        <textarea class="form-control"
                                                                  rows="3" name="description" id="body"></textarea>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>

                                    </div>

                                </div>
                                <hr>
                                <button type="submit" class="btn btn-block btn-info btn-lg">Create</button>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div class="card card-blue collapsed-card">
                                <div class="card-header ">
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                                class="fas fa-plus"></i></button>
                                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                                    </div>
                                    <h3 class="card-title">SEO</h3>
                                </div>
                                <div class="card-body">
                                    <div class="input-group mb-3">

                                    </div>

                                    <div class="form-group">
                                        <label>SEO Title</label>
                                    </div>
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="" name="seo_title"
                                        >
                                    </div>

                                    <div class="form-group">
                                        <label>SEO Description</label>
                                        <textarea class="form-control" rows="3"
                                                  name="seo_description"></textarea>
                                    </div>


                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>
@stop


@section('scripts')
    <script src="{{asset('rpanel/plugins/select2/js/select2.full.min.js')}}"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2({
                theme: 'bootstrap4'
            });
            $('#tags').select2({
                theme: 'bootstrap4',
                tags: true,
                // data: ["Clare","Cork","South Dublin"],
                tokenSeparators: [','],

                /* the next 2 lines make sure the user can click away after typing and not lose the new tag */

            });
        });



    </script>
    <script src="{{asset('rpanel/tinymce/tinymce.min.js')}}"></script>
    <script>
        tinymce.init({
            selector: '#body',
            height: 500,
            menubar: true,
            plugins: [
                'advlist autolink lists link image charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code help wordcount codesample', 'code image'
            ],
            toolbar: 'image code | codesample | insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'],
            image_title: true,
            automatic_uploads: true,
            images_upload_url: '{{route('rpanel.uploadimage')}}',
            file_picker_types: 'image',
            document_base_url : "/",
            relative_urls : false,
            remove_script_host : false,
            images_upload_base_path: '',
            images_upload_credentials: true,
            file_picker_callback: function(cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');
                input.onchange = function() {
                    var file = this.files[0];
                    var reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);
                        cb(blobInfo.blobUri(), { title: file.name });
                        console.log(blobInfo);
                    };
                };


            }
        });
        let img = tinymce.selection.getNode();


    </script>

@endsection


@section('css')
    <link rel="stylesheet" href="{{asset('rpanel/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('rpanel/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <style>
        .select2-results__option[aria-selected=true] {
            display: none;
        }
    </style>

@endsection

resources/views/rpanel/blog/category/index.blade.php
@extends('rpanel.layouts.app')

@section('title','New Category')

@section('content')
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">All Categories</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">

                <a href="{{route('rpanel.category.create')}}">
                    <button type="button" class="btn btn-info btn-sm">Create</button>
                </a>
                <hr>
                <table class="table table-condensed">
                    <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Main Category?</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @forelse($categories as $category)
                    <tr>
                        <td>{{$category->id}}</td>
                        <td>{{$category->name}}</td>
                        <td>{{$category->slug}}</td>
                        <td>{{$category->parent_id ? $category->parent->name : 'Yes'}}</td>
                        <td class="project-actions">
                            <a class="btn btn-primary btn-sm" href="#" target="_blank">
                                <i class="fas fa-folder"></i>View

                            </a>
                            <a class="btn btn-info btn-sm" href="{{route('rpanel.category.edit',$category->id)}}">
                                <i class="fas fa-pencil-alt"></i>Edit
                            </a>
                            <a class="btn btn-danger btn-sm" href="" data-toggle="modal"
                               data-target="#modal-danger-{{$category->id}}">
                                <i class="fas fa-trash"></i>Delete
                            </a>
                        </td>
                    </tr>
                    <div class="modal fade" id="modal-danger-{{$category->id}}">
                        <div class="modal-dialog">
                            <div class="modal-content bg-danger">
                                <div class="modal-header">
                                    <h4 class="modal-title">Delete?</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <div class="modal-footer justify-content-between">
                                    <form action="{{route('rpanel.category.destroy',$category->id)}}"
                                          method="POST">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                    <button type="button" class="btn btn-outline-light"
                                            data-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>

                    @empty

                    @endforelse

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
@stop